---
apiVersion: apps/v1
kind:  Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    author: hbc
spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres-deployment
  template:
    metadata:
      name: postgres-pod
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPost: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES-USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbname

...
