---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    author: hbc
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-deplyment
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-deployment
    spec:
      - containers:
          - name: redis
            image:  redis
            port:
              - containerPort:  6379
...