---
apiVersion: v1
kind: Service
metadat:
  name: result-app-deployment-service
spec:
  type: LoadBalancer
  ports:
    - targertPort: 80
      port: 80
  selector:
    name:  result-app-deployment

...